#!/usr/bin/env bash

set -e

if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-lool}:x:$(id -u):0:${USER_NAME:-lool} user:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
fi

cp /etc/config/loolwsd.xml /etc/loolwsd/loolwsd.xml

perl -pi -e "s/<username (.*)>.*<\/username>/<username \1>${USERNAME}<\/username>/" /etc/loolwsd/loolwsd.xml
perl -pi -e "s/<password (.*)>.*<\/password>/<password \1>${PASSWORD}<\/password>/" /etc/loolwsd/loolwsd.xml

exec /usr/bin/loolwsd \
  --version \
  --o:sys_template_path=/opt/lool/systemplate \
  --o:lo_template_path=/opt/libreoffice \
  --o:child_root_path=/opt/lool/child-roots \
  --o:file_server_root_path=/usr/share/loolwsd
